name: Git Desktop Browser

on:
  push:
  pull_request:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  lint:
    runs-on: windows-latest

    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: actions/checkout@v3

      - name: Check if package-lock.json is up to date
        run: npx --yes package-lock-utd@1.x.x

      - name: Install dependencies
        run: npm ci

      - name: Run the linter
        run: npm run lint

  build:
    needs: lint

    runs-on: windows-latest

    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Build the project
        run: npm run build --workspaces

      - name: Create the exe file
        run: npm run make-prod

  make-windows:
    if: github.event_name == 'release'
    needs: build

    runs-on: windows-latest

    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Create the exe file
        run: npm run make-prod

      - uses: actions/upload-artifact@v3
        with:
          name: Git Desktop Browser.exe
          path: out/prod/make/squirrel.windows/x64/*.exe
