name: Git Desktop Browser

on: [push, pull_request, workflow_dispatch]

jobs:
  lint:
    name: Lint everything
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: actions/checkout@v3

      - name: Check if package-lock.json is up to date
        run: npx --yes package-lock-utd@1.x.x

      - name: Install dependencies
        run: npm ci

      - name: Run the linter
        run: npm run lint

  build:
    name: Build the frontend
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Build the project
        run: npm run build --workspaces
